library(dplyr)
library(lubridate)


data<-read.table("household_power_consumption.txt",sep=";",header=TRUE, na.strings="?",colClasses="character",stringsAsFactors=FALSE)

cran<-tbl_df(data)
mehvesh<-filter(cran,Date=="1/2/2007"|Date=="2/2/2007")
mehvi<-mutate(mehvesh,datentime=dmy(Date)+hms(Time))
x<-as.POSIXlt(mehvi$datentime)
rabia<-cbind(mehvi,x)
par(mfrow=c(2,2),mar=c(4,4,4,4),adj=0.5,cex=0.7)
with(rabia,plot(x,Global_active_power,ylab="Global Active Power(kilowatts)",xlab="",type="l"))
with(rabia,plot(x,Voltage,ylab="Voltage",xlab="datetime",type="l"))
with(rabia,plot(x,Sub_metering_1,type="n",xlab="",ylab="Energy sub metering"))
with(rabia,lines(x,Sub_metering_1))
with(rabia,lines(x,Sub_metering_2,col="red"))
with(rabia,lines(x,Sub_metering_3,col="blue"))
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(rabia,plot(x,Global_reactive_power,ylab="Global_Reactive_Power",xlab="datetime",type="l"))
dev.copy(png,file="plot4.png")
png(filename="plot4.png", width=480, height=480)
dev.off()